### ISSUE TITLE
specific rules for specific IP address

### ISSUE THREAD

**Issue by dimthe** [geerlingguy/ansible-role-firewall#23]
i want to edit this role to allow me to block or allow ports for several IPs. For example , allow 22 for 192.168.1.2 but block 22 for 1.3 etc 

any tips ?
thanks

**Comment by geerlingguy** [comment]
Sure thing! I do this often for custom firewall rules, so I'll go grab a few examples:

``` yaml
# Allow only the IP 167.89.89.18 to access port 4949 (Munin).
firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4949 -s 167.89.89.18 -j ACCEPT"

# Allow only the IP 214.192.48.21 to access port 3306 (MySQL).
firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 3306 -s 214.192.48.21 -j ACCEPT"
```
