### ISSUE TITLE
Error on Debian on first check_mode run

### ISSUE THREAD

**Issue by Al-thi** [geerlingguy/ansible-role-firewall#95]
Hello,

This role fails on Debian when playing the following tasks in check_mode on a fresh server :

```yaml
- name: Configure the firewall service.
  service:
    name: firewall
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled_at_boot }}"
```

with the following error message :
```
fatal: [xxx]: FAILED! => {"changed": false, "msg": "Could not find the requested service firewall: host"}
```

because the firewall service unit file is not installed and therefore the service step fails.

I suggest adding the following line to this task to ignore check_mode errors :
```yaml
  ignore_errors: "{{ ansible_check_mode }}"
```
